export const DEFAULT_CATEGORIES = [
    { id: 'dc-1', name: 'Programming Languages', color: 'blue'   },
    { id: 'dc-2', name: 'Data & Analytics',       color: 'green'  },
    { id: 'dc-3', name: 'AI & Machine Learning',  color: 'purple' },
    { id: 'dc-4', name: 'Cloud & DevOps',         color: 'orange' },
    { id: 'dc-5', name: 'Web Development',        color: 'cyan'   },
    { id: 'dc-6', name: 'Productivity & Tools',   color: 'yellow' },
    { id: 'dc-7', name: 'Design & UX',            color: 'pink'   },
    { id: 'dc-8', name: 'Cybersecurity',          color: 'red'    },
];

export const DEFAULT_SKILLS = [
    // Programming Languages
    { id: 'ds-1',  name: 'Python',               categoryId: 'dc-1' },
    { id: 'ds-2',  name: 'Java',                 categoryId: 'dc-1' },
    { id: 'ds-3',  name: 'JavaScript',           categoryId: 'dc-1' },
    { id: 'ds-4',  name: 'TypeScript',           categoryId: 'dc-1' },
    { id: 'ds-5',  name: 'C++',                  categoryId: 'dc-1' },
    { id: 'ds-6',  name: 'C#',                   categoryId: 'dc-1' },
    { id: 'ds-7',  name: 'R',                    categoryId: 'dc-1' },
    { id: 'ds-8',  name: 'Go',                   categoryId: 'dc-1' },
    { id: 'ds-9',  name: 'Swift',                categoryId: 'dc-1' },
    { id: 'ds-10', name: 'Kotlin',               categoryId: 'dc-1' },
    { id: 'ds-11', name: 'SQL',                  categoryId: 'dc-1' },
    { id: 'ds-12', name: 'PHP',                  categoryId: 'dc-1' },
    { id: 'ds-13', name: 'Rust',                 categoryId: 'dc-1' },
    { id: 'ds-14', name: 'Scala',                categoryId: 'dc-1' },
    { id: 'ds-15', name: 'MATLAB',               categoryId: 'dc-1' },
    // Data & Analytics
    { id: 'ds-16', name: 'Power BI',             categoryId: 'dc-2' },
    { id: 'ds-17', name: 'Tableau',              categoryId: 'dc-2' },
    { id: 'ds-18', name: 'Excel',                categoryId: 'dc-2' },
    { id: 'ds-19', name: 'Google Analytics',     categoryId: 'dc-2' },
    { id: 'ds-20', name: 'Looker',               categoryId: 'dc-2' },
    { id: 'ds-21', name: 'Google Data Studio',   categoryId: 'dc-2' },
    { id: 'ds-22', name: 'Alteryx',              categoryId: 'dc-2' },
    { id: 'ds-23', name: 'Apache Spark',         categoryId: 'dc-2' },
    { id: 'ds-24', name: 'Pandas',               categoryId: 'dc-2' },
    { id: 'ds-25', name: 'NumPy',                categoryId: 'dc-2' },
    { id: 'ds-26', name: 'Statistics',           categoryId: 'dc-2' },
    { id: 'ds-27', name: 'Qlik',                 categoryId: 'dc-2' },
    { id: 'ds-28', name: 'dbt',                  categoryId: 'dc-2' },
    // AI & Machine Learning
    { id: 'ds-29', name: 'Machine Learning',      categoryId: 'dc-3' },
    { id: 'ds-30', name: 'Deep Learning',         categoryId: 'dc-3' },
    { id: 'ds-31', name: 'NLP',                   categoryId: 'dc-3' },
    { id: 'ds-32', name: 'Computer Vision',       categoryId: 'dc-3' },
    { id: 'ds-33', name: 'Generative AI',         categoryId: 'dc-3' },
    { id: 'ds-34', name: 'TensorFlow',            categoryId: 'dc-3' },
    { id: 'ds-35', name: 'PyTorch',               categoryId: 'dc-3' },
    { id: 'ds-36', name: 'Scikit-learn',          categoryId: 'dc-3' },
    { id: 'ds-37', name: 'Hugging Face',          categoryId: 'dc-3' },
    { id: 'ds-38', name: 'Prompt Engineering',    categoryId: 'dc-3' },
    { id: 'ds-39', name: 'MLOps',                 categoryId: 'dc-3' },
    { id: 'ds-40', name: 'Reinforcement Learning',categoryId: 'dc-3' },
    { id: 'ds-41', name: 'LLMs',                  categoryId: 'dc-3' },
    { id: 'ds-42', name: 'RAG',                   categoryId: 'dc-3' },
    // Cloud & DevOps
    { id: 'ds-43', name: 'AWS',                   categoryId: 'dc-4' },
    { id: 'ds-44', name: 'Azure',                 categoryId: 'dc-4' },
    { id: 'ds-45', name: 'Google Cloud',          categoryId: 'dc-4' },
    { id: 'ds-46', name: 'Docker',                categoryId: 'dc-4' },
    { id: 'ds-47', name: 'Kubernetes',            categoryId: 'dc-4' },
    { id: 'ds-48', name: 'Terraform',             categoryId: 'dc-4' },
    { id: 'ds-49', name: 'CI/CD',                 categoryId: 'dc-4' },
    { id: 'ds-50', name: 'Jenkins',               categoryId: 'dc-4' },
    { id: 'ds-51', name: 'Git',                   categoryId: 'dc-4' },
    { id: 'ds-52', name: 'Linux',                 categoryId: 'dc-4' },
    { id: 'ds-53', name: 'Ansible',               categoryId: 'dc-4' },
    { id: 'ds-54', name: 'GitHub Actions',        categoryId: 'dc-4' },
    // Web Development
    { id: 'ds-55', name: 'HTML & CSS',            categoryId: 'dc-5' },
    { id: 'ds-56', name: 'React',                 categoryId: 'dc-5' },
    { id: 'ds-57', name: 'Angular',               categoryId: 'dc-5' },
    { id: 'ds-58', name: 'Vue.js',                categoryId: 'dc-5' },
    { id: 'ds-59', name: 'Node.js',               categoryId: 'dc-5' },
    { id: 'ds-60', name: 'Next.js',               categoryId: 'dc-5' },
    { id: 'ds-61', name: 'Django',                categoryId: 'dc-5' },
    { id: 'ds-62', name: 'Flask',                 categoryId: 'dc-5' },
    { id: 'ds-63', name: 'FastAPI',               categoryId: 'dc-5' },
    { id: 'ds-64', name: 'REST APIs',             categoryId: 'dc-5' },
    { id: 'ds-65', name: 'GraphQL',               categoryId: 'dc-5' },
    { id: 'ds-66', name: 'Tailwind CSS',          categoryId: 'dc-5' },
    { id: 'ds-67', name: 'Bootstrap',             categoryId: 'dc-5' },
    // Productivity & Tools
    { id: 'ds-68', name: 'Microsoft Office',      categoryId: 'dc-6' },
    { id: 'ds-69', name: 'Google Workspace',      categoryId: 'dc-6' },
    { id: 'ds-70', name: 'Notion',                categoryId: 'dc-6' },
    { id: 'ds-71', name: 'Jira',                  categoryId: 'dc-6' },
    { id: 'ds-72', name: 'Confluence',            categoryId: 'dc-6' },
    { id: 'ds-73', name: 'Trello',                categoryId: 'dc-6' },
    { id: 'ds-74', name: 'Asana',                 categoryId: 'dc-6' },
    { id: 'ds-75', name: 'Slack',                 categoryId: 'dc-6' },
    { id: 'ds-76', name: 'Power Automate',        categoryId: 'dc-6' },
    { id: 'ds-77', name: 'Power Apps',            categoryId: 'dc-6' },
    { id: 'ds-78', name: 'SharePoint',            categoryId: 'dc-6' },
    // Design & UX
    { id: 'ds-79', name: 'Figma',                 categoryId: 'dc-7' },
    { id: 'ds-80', name: 'Adobe XD',              categoryId: 'dc-7' },
    { id: 'ds-81', name: 'Canva',                 categoryId: 'dc-7' },
    { id: 'ds-82', name: 'UI/UX Design',          categoryId: 'dc-7' },
    { id: 'ds-83', name: 'Wireframing',           categoryId: 'dc-7' },
    { id: 'ds-84', name: 'Prototyping',           categoryId: 'dc-7' },
    { id: 'ds-85', name: 'Adobe Photoshop',       categoryId: 'dc-7' },
    { id: 'ds-86', name: 'Adobe Illustrator',     categoryId: 'dc-7' },
    { id: 'ds-87', name: 'Sketch',                categoryId: 'dc-7' },
    // Cybersecurity
    { id: 'ds-88', name: 'Network Security',      categoryId: 'dc-8' },
    { id: 'ds-89', name: 'Ethical Hacking',       categoryId: 'dc-8' },
    { id: 'ds-90', name: 'Penetration Testing',   categoryId: 'dc-8' },
    { id: 'ds-91', name: 'CISSP',                 categoryId: 'dc-8' },
    { id: 'ds-92', name: 'SOC Analysis',          categoryId: 'dc-8' },
    { id: 'ds-93', name: 'Cryptography',          categoryId: 'dc-8' },
    { id: 'ds-94', name: 'SIEM',                  categoryId: 'dc-8' },
    { id: 'ds-95', name: 'Cloud Security',        categoryId: 'dc-8' },
    { id: 'ds-96', name: 'Zero Trust',            categoryId: 'dc-8' },
];
